clean: true

theme: fullwidth

output: docs
readme: README.md

module: ColorComponents
swift_build_tool: spm
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/color-components

author: ser.soft GmbH
author_url: https://sersoft.de
