#if !canImport(ObjectiveC)
import XCTest

extension ImageColorsCalculatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageColorsCalculatorTests = [
        ("testAverageColor", testAverageColor),
        ("testCGImageInitializer", testCGImageInitializer),
        ("testMaxComponentColor", testMaxComponentColor),
        ("testMostProminentColor", testMostProminentColor),
        ("testNSImageInitializer", testNSImageInitializer),
        ("testProminentColorsPerformanceWithLinearSRGBDifference", testProminentColorsPerformanceWithLinearSRGBDifference),
        ("testProminentColorsPerformanceWithWeightedSRGBDifference", testProminentColorsPerformanceWithWeightedSRGBDifference),
        ("testUIImageInitializer", testUIImageInitializer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ImageColorsCalculatorTests.__allTests__ImageColorsCalculatorTests),
    ]
}
#endif
