#if !canImport(ObjectiveC)
import XCTest

extension BWATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWATests = [
        ("testExactFloatToFloatConversion", testExactFloatToFloatConversion),
        ("testExactFloatToIntegerConversion", testExactFloatToIntegerConversion),
        ("testExactIntegerToFloatConversion", testExactIntegerToFloatConversion),
        ("testExactIntegerToIntegerConversion", testExactIntegerToIntegerConversion),
        ("testFloatingPointColorComponentsConformance", testFloatingPointColorComponentsConformance),
        ("testFloatToFloatConversion", testFloatToFloatConversion),
        ("testFloatToIntegerConversion", testFloatToIntegerConversion),
        ("testIntegerToFloatConversion", testIntegerToFloatConversion),
        ("testIntegerToIntegerConversion", testIntegerToIntegerConversion),
        ("testModification", testModification),
        ("testSimpleCreation", testSimpleCreation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BWATests.__allTests__BWATests),
    ]
}
#endif
