#if !canImport(ObjectiveC)
import XCTest

extension BWATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWATests = [
        ("testExactFloatToFloatConversion", testExactFloatToFloatConversion),
        ("testExactFloatToIntegerConversion", testExactFloatToIntegerConversion),
        ("testExactIntegerToFloatConversion", testExactIntegerToFloatConversion),
        ("testExactIntegerToIntegerConversion", testExactIntegerToIntegerConversion),
        ("testFloatingPointColorComponentsConformance", testFloatingPointColorComponentsConformance),
        ("testFloatToFloatConversion", testFloatToFloatConversion),
        ("testFloatToIntegerConversion", testFloatToIntegerConversion),
        ("testIntegerToFloatConversion", testIntegerToFloatConversion),
        ("testIntegerToIntegerConversion", testIntegerToIntegerConversion),
        ("testModification", testModification),
        ("testSimpleCreation", testSimpleCreation),
    ]
}

extension BWA_AppKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWA_AppKitTests = [
        ("testCreationFromNSColor", testCreationFromNSColor),
        ("testNSColorCreation", testNSColorCreation),
    ]
}

extension BWA_CoreGraphicsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWA_CoreGraphicsTests = [
        ("testCGColorCreation", testCGColorCreation),
        ("testCreationFromCGColor", testCreationFromCGColor),
    ]
}

extension BWA_SwiftUITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWA_SwiftUITests = [
        ("testColorCreation", testColorCreation),
        ("testCreationFromColor", testCreationFromColor),
    ]
}

extension BWA_UIKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BWA_UIKitTests = [
        ("testCreationFromUIColor", testCreationFromUIColor),
        ("testUIColorCreation", testUIColorCreation),
    ]
}

extension ColorComponentsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorComponentsTests = [
        ("testBrightColorCheck", testBrightColorCheck),
        ("testClearColorCheck", testClearColorCheck),
    ]
}

extension HSBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBATests = [
        ("testExactFloatToFloatConversion", testExactFloatToFloatConversion),
        ("testExactFloatToIntegerConversion", testExactFloatToIntegerConversion),
        ("testExactIntegerToFloatConversion", testExactIntegerToFloatConversion),
        ("testExactIntegerToIntegerConversion", testExactIntegerToIntegerConversion),
        ("testFloatingPointColorComponentsConformance", testFloatingPointColorComponentsConformance),
        ("testFloatToFloatConversion", testFloatToFloatConversion),
        ("testFloatToIntegerConversion", testFloatToIntegerConversion),
        ("testIntegerToFloatConversion", testIntegerToFloatConversion),
        ("testIntegerToIntegerConversion", testIntegerToIntegerConversion),
        ("testModification", testModification),
        ("testSimpleCreation", testSimpleCreation),
    ]
}

extension HSBA_AppKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBA_AppKitTests = [
        ("testCreationFromNSColor", testCreationFromNSColor),
        ("testNSColorCreation", testNSColorCreation),
    ]
}

extension HSBA_CoreGraphicsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBA_CoreGraphicsTests = [
        ("testCGColorCreation", testCGColorCreation),
        ("testCreationFromCGColor", testCreationFromCGColor),
    ]
}

extension HSBA_RGBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBA_RGBATests = [
        ("testCreationFromRGBA_BlueMax", testCreationFromRGBA_BlueMax),
        ("testCreationFromRGBA_DeltaZero", testCreationFromRGBA_DeltaZero),
        ("testCreationFromRGBA_GreenMax", testCreationFromRGBA_GreenMax),
        ("testCreationFromRGBA_MaxZero", testCreationFromRGBA_MaxZero),
        ("testCreationFromRGBA_RedMax", testCreationFromRGBA_RedMax),
    ]
}

extension HSBA_SwiftUITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBA_SwiftUITests = [
        ("testColorCreation", testColorCreation),
        ("testCreationFromColor", testCreationFromColor),
    ]
}

extension HSBA_UIKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HSBA_UIKitTests = [
        ("testCreationFromUIColor", testCreationFromUIColor),
        ("testUIColorCreation", testUIColorCreation),
    ]
}

extension RGBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBATests = [
        ("testExactFloatToFloatConversion", testExactFloatToFloatConversion),
        ("testExactFloatToIntegerConversion", testExactFloatToIntegerConversion),
        ("testExactIntegerToFloatConversion", testExactIntegerToFloatConversion),
        ("testExactIntegerToIntegerConversion", testExactIntegerToIntegerConversion),
        ("testFloatingPointColorComponentsConformance", testFloatingPointColorComponentsConformance),
        ("testFloatToFloatConversion", testFloatToFloatConversion),
        ("testFloatToIntegerConversion", testFloatToIntegerConversion),
        ("testIntegerToFloatConversion", testIntegerToFloatConversion),
        ("testIntegerToIntegerConversion", testIntegerToIntegerConversion),
        ("testModification", testModification),
        ("testSimpleCreation", testSimpleCreation),
    ]
}

extension RGBA_AppKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_AppKitTests = [
        ("testCreationFromNSColor", testCreationFromNSColor),
        ("testNSColorCreation", testNSColorCreation),
    ]
}

extension RGBA_CoreGraphicsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_CoreGraphicsTests = [
        ("testCGColorCreation", testCGColorCreation),
        ("testCreationFromCGColor", testCreationFromCGColor),
        ("testCreationFromCGColorConvertingColorSpaces", testCreationFromCGColorConvertingColorSpaces),
    ]
}

extension RGBA_HSBATests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_HSBATests = [
        ("testCreationFromHSBA_FifthPart", testCreationFromHSBA_FifthPart),
        ("testCreationFromHSBA_FirstPart", testCreationFromHSBA_FirstPart),
        ("testCreationFromHSBA_FourthPart", testCreationFromHSBA_FourthPart),
        ("testCreationFromHSBA_SecondPart", testCreationFromHSBA_SecondPart),
        ("testCreationFromHSBA_SixthPart", testCreationFromHSBA_SixthPart),
        ("testCreationFromHSBA_ThirdPart", testCreationFromHSBA_ThirdPart),
    ]
}

extension RGBA_HexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_HexTests = [
        ("testCreationFromHex", testCreationFromHex),
        ("testHexString", testHexString),
    ]
}

extension RGBA_SwiftUITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_SwiftUITests = [
        ("testColorCreation", testColorCreation),
        ("testCreationFromColor", testCreationFromColor),
    ]
}

extension RGBA_UIKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RGBA_UIKitTests = [
        ("testCreationFromUIColor", testCreationFromUIColor),
        ("testUIColorCreation", testUIColorCreation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BWATests.__allTests__BWATests),
        testCase(BWA_AppKitTests.__allTests__BWA_AppKitTests),
        testCase(BWA_CoreGraphicsTests.__allTests__BWA_CoreGraphicsTests),
        testCase(BWA_SwiftUITests.__allTests__BWA_SwiftUITests),
        testCase(BWA_UIKitTests.__allTests__BWA_UIKitTests),
        testCase(ColorComponentsTests.__allTests__ColorComponentsTests),
        testCase(HSBATests.__allTests__HSBATests),
        testCase(HSBA_AppKitTests.__allTests__HSBA_AppKitTests),
        testCase(HSBA_CoreGraphicsTests.__allTests__HSBA_CoreGraphicsTests),
        testCase(HSBA_RGBATests.__allTests__HSBA_RGBATests),
        testCase(HSBA_SwiftUITests.__allTests__HSBA_SwiftUITests),
        testCase(HSBA_UIKitTests.__allTests__HSBA_UIKitTests),
        testCase(RGBATests.__allTests__RGBATests),
        testCase(RGBA_AppKitTests.__allTests__RGBA_AppKitTests),
        testCase(RGBA_CoreGraphicsTests.__allTests__RGBA_CoreGraphicsTests),
        testCase(RGBA_HSBATests.__allTests__RGBA_HSBATests),
        testCase(RGBA_HexTests.__allTests__RGBA_HexTests),
        testCase(RGBA_SwiftUITests.__allTests__RGBA_SwiftUITests),
        testCase(RGBA_UIKitTests.__allTests__RGBA_UIKitTests),
    ]
}
#endif
